[package]
name = "rust_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.0", features = ["rwh_05"] }
ash = "0.38.0"
env_logger = { version = "0.11.3", optional = true }
log = "0.4.21"

[features]
gfx_debug_msg = ['env_logger']